from .structs import Coin

ENJ = Coin("ENJ")
CRO = Coin("CRO")
KNC = Coin("KNC")
VET = Coin("VET")
PAXG = Coin("PAXG")
USDT = Coin("USDT")
ALGO = Coin("ALGO")
ATOM = Coin("ATOM")
COMP = Coin("COMP")
UNI = Coin("UNI")
AAVE = Coin("AAVE")
WBTC = Coin("WBTC")
XRP = Coin("XRP")
XLM = Coin("XLM")
LINK = Coin("LINK")
YFI = Coin("YFI")
QTUM = Coin("QTUM")
XTZ = Coin("XTZ")
MANA = Coin("MANA")
BCH = Coin("BCH")
EOS = Coin("EOS")
OMG = Coin("OMG")
BAND = Coin("BAND")
DAI = Coin("DAI")
BTC = Coin("BTC")
ETC = Coin("ETC")
MKR = Coin("MKR")
BAT = Coin("BAT")
CELR = Coin("CELR")
ETH = Coin("ETH")
MCO = Coin("MCO")
NEO = Coin("NEO")
LTC = Coin("LTC")
EGLD = Coin("EGLD")
USDC = Coin("USDC")
ADA = Coin("ADA")
ICX = Coin("ICX")
DOT = Coin("DOT")
REN = Coin("REN")


def all():
    return [
        value for name, value in globals().items()
        if isinstance(value, Coin)
    ]
